[package]
name = "simp_hom_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
ndarray = "0.15.4"
ndarray-rand = "0.14.0"
nom = "7.1.1"
